config/routes.rb
Rails.application.routes.draw do

  resources :attendees
  resources :tickets
  resources :ticket_types
  get "events/:id/downloads" => "events#calendar_download", as: 'event_calendar_download'
  get "event/:year/:month/:day" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ }
  get "event/:year/:month/:day/*anything" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ }
  get 'privacy' => 'home#privacy',  :defaults => { :id => '2' }, as: 'privacy'
  get 'news/:id/edit' => 'news#edit'
  get 'communities/:id/edit' => 'communities#edit'
  get 'news/:id/*anything' => 'news#show', as: 'news_custom'
  get 'communities/:id/*anything' => 'communities#show', as: 'community_custom'
  get 'user/:id/*anything' => 'user#show', as: 'user_custom'
  resources :events do
    resources :attendees, only: [:index]
  end
  resources :user, only: [:show]
  resources :communities
  resources :carousels
  resources :pages
   mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :news
  get 'home/index'

  devise_for :users,  :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/views/shared/_carousel.slim
div class="container"
  div class="splash"
     div id="myCarousel" class="carousel slide"
      div class="carousel-inner"
        - count=0
        - @page.carousels.each do |row|
          - item_class = count==0 ? {class: "item active"} : {class: "item"}
          div *item_class
            - count=1
            = image_tag row.image.url(:carousel)
            div class="container"
              div class="carousel-caption"
                h1 = row.header
                p class="lead"
                  = row.sentence
                - unless row.link.empty?
                  = link_to t(:goto), row.link, class: "btn btn-lage btn-primary" 
        a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;
        a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;

app/views/shared/_footer.slim
div class="container"
  div class="row"
    div class="col-lg-12"
      ul class="list-unstyled"
        li class="pull-right"
          = link_to t(:back_to_top), "#top"
        li = link_to t(:privacy), privacy_path
        li = link_to "Wiki", "https://wiki.floss-pa.net"

app/views/shared/_header.slim
div class="container"
 div class="row"
  div class="navbar-header"
    a href="../" class="navbar-brand"  = image_tag "logo.png", alt: "floss-pa", class: "img-fluid"
    button class="navbar-toggle" data-toggle="collapse" data-target="#navbar-main"
      span class="icon-bar"
      span class="icon-bar"
      span class="icon-bar"

  div  class="navbar-collapse collapse" id="navbar-main"
    ul class="nav navbar-nav"
      li = link_to t(:news), news_index_path
      li = link_to t(:communities), communities_path
      li = link_to t(:events), events_path
      li = link_to "Wiki", "https://wiki.floss-pa.net/",{:target=>"_blank"}

    ul class="nav navbar-nav navbar-right"

      - unless user_signed_in?

        li = link_to t(:sign_up), new_user_registration_path
        li = link_to t(:sign_in), new_user_session_path

      - else

        - if current_user.has_role? :admin

          li class="dropdown"
            a class="dropdown-toggle" data-toggle="dropdown" href="#" id="user"
              | Admin
              span class="caret"
            ul class="dropdown-menu" aria-labelledby="user"
             li = link_to t(:pages), pages_path
             li = link_to t(:carousel), carousels_path

        li class="dropdown"
          a class="dropdown-toggle" data-toggle="dropdown" href="#" id="user"
            - if current_user.avatar.blank?
              = current_user.name
            - else
              = image_tag current_user.avatar.url(:thumb), class: "img-circle", height: 20
            span class="caret"

          ul class="dropdown-menu" aria-labelledby="user"
            / li = link_to t(:profile), user_path(current_user)
            / li = link_to t(:edit) + ' ' + t(:profile), edit_user_path(current_user)
            li = link_to t(:add_news), new_news_path
            li = link_to t(:add_community), new_community_path
            li = link_to t(:add_event), new_event_path
            li = link_to t(:account), edit_user_registration_path
            li = link_to t(:sign_out), destroy_user_session_path, {:method=>"delete", :id=>"logout"}