config/routes.rb
Rails.application.routes.draw do

  resources :attendees
  resources :tickets
  resources :ticket_types
  get "events/:id/downloads" => "events#calendar_download", as: 'event_calendar_download'
  get "event/:year/:month/:day" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ }
  get "event/:year/:month/:day/*anything" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ }
  get 'privacy' => 'home#privacy',  :defaults => { :id => '2' }, as: 'privacy'
  get 'news/:id/edit' => 'news#edit'
  get 'communities/:id/edit' => 'communities#edit'
  get 'news/:id/*anything' => 'news#show', as: 'news_custom'
  get 'communities/:id/*anything' => 'communities#show', as: 'community_custom'
  get 'user/:id/*anything' => 'user#show', as: 'user_custom'
  resources :events do
    resources :attendees, only: [:index]
  end
  resources :user, only: [:show]
  resources :communities
  resources :carousels
  resources :pages
   mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :news
  get 'home/index'

  devise_for :users,  :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  #belongs_to :community
  has_many :tickets #, inverse_of: :event
  has_many :attendees, :through => :tickets
  date_time_attribute :start_at
  date_time_attribute :end_at
  validates :title, presence: true, length: { minimum: 8}
  validates :description, presence: true, length: { minimum: 10}
  validates :start_at, presence: true
  validates :end_at, presence: true
  has_attached_file :image,
    styles: { :event=>"1200x500",:ticket=> "600x250", :project=>"320x175",:medium => "200x200>" } ,
     :processors => [:cropper],
     :default_style => :event,
     default_url: ->(attachment) { ActionController::Base.helpers.asset_path("event_default.png") }
  validates_attachment_content_type :image, :content_type => /^image\/(png|jpeg|jpg)/
  accepts_nested_attributes_for :tickets
  attr_accessor :crop_x, :crop_y, :crop_x2, :crop_y2, :crop_w, :crop_h, :crop_vy
  after_update :reprocess_image, :if => :cropping?
  after_create :reprocess_image, :if => :cropping?

  def create_calendar_entry
    cal = Icalendar::Calendar.new
      cal.timezone do |t|
        t.tzid = "America/Panama"
      end
      cal.event do |e|
        e.dtstart = Icalendar::Values::DateTime.new(self.start_at)
        e.dtend = Icalendar::Values::DateTime.new(self.end_at)
        e.summary = self.title
        e.description = self.description
        e.ip_class = "PRIVATE"
      end
      cal
  end

  private

  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  def image_geometry(style = :original)
    tmpfile = image.queued_for_write[style]
    @geometry ||= {}
    @geometry[style] ||= Paperclip::Geometry.from_file(tmpfile)
  end

  def reprocess_image
    image_geometry(:original)
    self.crop_h = 500
    self.crop_w = 1200
    self.crop_y = (@geometry[:original].height.to_f * (self.crop_y.to_f / self.crop_vy.to_f)).to_i
    self.crop_x = (@geometry[:original].width.to_f * (self.crop_x.to_f / 1100.to_f)).to_i
    image.assign(image)
    image.save
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index,:show,:calendar_download]
  before_action :set_event, only: [:show, :edit, :update, :destroy, :download]
  skip_authorization_check :only => [:calendar_download]
  load_and_authorize_resource

  # GET /events
  # GET /events.json
  def index
     if Date.valid_date? params[:year].to_i, params[:month].to_i, params[:day].to_i
      event_date = Date.parse("#{params[:year]}.#{params[:month]}.#{params[:day]}")
     end
     unless event_date.nil?
      @events = Event.paginate(:page => params[:page],:per_page => 8).where("publish=true and date(start_at)=?",event_date).order('start_at Desc')
     else
     @events = Event.paginate(:page => params[:page],:per_page =>8 ).where("publish=true ", params[:id]).order('start_at DESC')
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    if user_signed_in?
      @attendee = @event.attendees.where(:user_id=>current_user).first
    end
    @available=false
    begin
      unless @event.tickets.first.amount.nil?
        amount = @event.tickets.first.amount - @event.attendees.count
        @available=true if amount>0
      end
    rescue

    end
    @community = Community.find(@event.community_id) unless @event.community_id.nil?
  end

  # GET /events/new
  def new
    @event = Event.new
    @tickets = @event.tickets.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def calendar_download
    cal = @event.create_calendar_entry
    filename = 'floss-pa-event.ics'
    send_data cal.to_ical, type: 'text/calendar', disposition: 'attachment', filename: filename
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:user_id, :title, :image, :location, :frecuency, :start_at_date, :start_at_time, :end_at_date,:end_at_time, :description, :keyworkds, :ticket_url, :community_id, :organizer, :publish, :latitude, :longitude, :crop_x, :crop_y, :crop_x2, :crop_y2, :crop_w, :crop_h, :crop_vy, tickets_attributes: [:id, :event_id, :ticket_type_id, :amount, :token])
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.slim
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      h2 = "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      ul
        - @event.errors.full_messages.each do |message|
          li = message

  div class="form-group row"
    = f.label t(:title), class: "form-input-label"
    = f.text_field :title, placeholder: t(:name_of_your_event), required: true, minimal: "10", class: "form-control"
    div class="text-warning"
      | * &nbsp;
      = t(:required)
  div class="form-group row"
    = f.label t(:start_at), class: "control-label"
    div class="form-group"
      div class="input-group col-lg-5"
        = f.text_field :start_at_date, value: (f.object.start_at_date.strftime("%Y-%m-%d") unless f.object.start_at.nil? ),required: true, "data-provide": "datepicker", "data-date-format": "yyyy-mm-dd", placeholder: DateTime.now.strftime("%Y-%m-%d"), class: "form-control"
        div class="input-group-addon"
           div class="input-group-text"
            i class="glyphicon glyphicon-calendar"
        div class="input-group"
          = f.text_field :start_at_time, size: 4, value: (f.object.start_at_time.strftime("%I:%M %p") unless f.object.start_at.nil? ), required: true, "data-provide": "timepicker", "data-default-time": DateTime.now.strftime("%I:%M %p"), placeholder: DateTime.now.strftime("%I:%M %p"), class: "form-control"
          div class='input-group-addon'
            div class="input-group-text"
              i class='glyphicon glyphicon-time'
    div class="text-warning"
      | * &nbsp;
      = t(:required)
  div class="form-group row"
    = f.label t(:end_at), class: "control-label"
    div class="form-group"
      div class="input-group col-lg-5"
        = f.text_field :end_at_date, value: (f.object.end_at_date.strftime("%Y-%m-%d") unless f.object.end_at.nil? ), required: true, "data-provide": "datepicker", "data-date-format": "yyyy-mm-dd", placeholder: DateTime.now.strftime("%Y-%m-%d"), class: "form-control"
        div class="input-group-addon"
           div class="input-group-text"
            i class="glyphicon glyphicon-calendar"
        div class="input-group"
          = f.text_field :end_at_time, size: 4, value: (f.object.start_at_time.strftime("%I:%M %p") unless f.object.end_at.nil?), required: true, "data-provide": "timepicker", "data-default-time": DateTime.now.strftime("%I:%M %p"), placeholder: DateTime.now.strftime("%I:%M %p"), class: "form-control"
          div class='input-group-addon'
            div class="input-group-text"
              i class='glyphicon glyphicon-time'
    div class="text-warning"
      | * &nbsp;
      = t(:required)
  div class="form-group row"
    = f.label t(:image), class: "form-input-label"
    = f.file_field :image, class: "form-control-file"
    = t(:event_image_information)
    - %w[x y x2 y2 w h vy].each do |attribute| 
     = f.hidden_field "crop_#{attribute}", id: "crop_#{attribute}"
    div id="Preview" class="text-center" 
     - if params[:action]==="edit"
        div class="thumbnail"
          = image_tag @event.image.url, id: "image"
  div class="form-group row"
    = f.label t(:location), class: "form-input-label"
    = f.text_field :location, placeholder: t(:place_where_your_event), required: true, minimal: 10, class: "form-control"
    div class="text-warning"
      | * &nbsp;
      = t(:required)
    div class="text-info"
      = t(:location_instruction)
  div class="form-group row"
    = f.hidden_field :latitude, class: "form-control"
    = f.hidden_field :longitude, class: "form-control"
    = map(center: {latlng: [8.984062, -79.521593],zoom: 14})
  div class="form-group row"
    = f.label t(:frecuency), class: "form-input-label"
    = f.text_field :frecuency, class: "form-control"
  div class="form-group row"
    = f.label t(:description), required: true, class: "form-input-label"
    = f.bootsy_area :description,rows: 20, class: "form-control"
  div class="form-group row"
    = f.label t(:keywords), placeholder: t(:keywords), class: "form-input-label"
    = f.text_field :keyworkds, placeholder: "Open Source, Fedora, Ruby, Security, etc", class: "form-control"
    div class="text-warning"
      | * &nbsp;
      = t(:required)
  div class="form-group row"
      = f.fields_for :tickets do |ticket_form|
       div class="col-lg-12"
        = ticket_form.label t(:tickets), class: "form-input-label"
        | :
       div class="col-lg-12" style="valign: middle"
        div class="col-lg-2"
          = ticket_form.label t(:ticket_type), class: "form-input-label"
          | :&nbsp;
        div class="col-lg-1"
          = ticket_form.select :ticket_type_id, TicketType.all.collect {|t| [t.name,t.id]}, class: "form-control"
        div class="col-lg-1"
          = ticket_form.label t(:ticket_amount), class: "form-input-label"
        div class="col-lg-1"
          = ticket_form.text_field :amount, size: 4, class: "form-control"
  div class="form-group row"
    = f.label t(:ticket_url), class: "form-input-label"
    = f.text_field :ticket_url, placeholder: t(:sample_ticket_url),type: "url", class: "form-control"
    div class="text-info"
      = t(:tickets_info)
  - unless current_user.communities.empty?
    div class="form-group row"
      = f.label t(:community), class: "form-input-label"
      | :&nbsp;
      = f.select :community_id, Community.all.collect {|c| [c.name,c.id]} , :include_blank => true, class: "form-control"
  - else
    div class="form-group row"
      = f.label t(:organizer), class: "form-input-label"
      = f.text_field :organizer, placeholder: t(:organizer_information), class: "form-control"
  div class="form-group row"
    = f.label t(:publish), class: "form-input-label"
    | &nbsp;
    = f.check_box :publish
  div class="form-group row"
    = f.submit t(:save), class: "btn btn-primary"

app/views/events/edit.html.slim
div class="container"
  div class="row"
     div class="bs-docs-section clearfix"
       div class="row"
         div class="page-header"
          div class="row"
           div class="jumbotron"
            div class="row"
             div class="col-lg-12"
               h2 class="display-3"
                 = t(:edit)
                 | &nbsp;
                 = t(:event)

               == render 'form'

               => link_to t(:show), @event
               '|
               =< link_to t(:back), events_path

app/views/events/index.html.slim
div class="clearfix"
  div class="container"
    div class="page-header"
      div class="row"
          h1
            = t(:events)
            | :
      div class="row"
          - @events.each do |event|
           div class="col-lg-6"
             div class="list-group"
              = link_to event_path(event), class: "list-group-item list-group-item-action flex-column align-items-start" do
                div class="d-flex w-100 justify-content-between"
                  h3 class="mb-1"
                    = event.title.truncate(46)
                  small class="text-muted "
                    / time_ago_in_words(event.created_at)
                div class="row"
                  div class="col-lg-4"
                    div class="text-center"
                      h1 class="display-2"
                        = event.start_at.strftime("%b")
                      h2 class="display-3 text-danger"
                        = event.start_at.strftime("%d")
                      h3 class="display-4"
                        = event.start_at.strftime("%Y")
                  div class="col-lg-8"
                    = image_tag event.image.url(:project), class: ""
                  div class="col-lg-12"
                    p
                      strong
                        = t(:location)
                        | :&nbsp;
                      = event.location.truncate(46)
                    p
                      strong
                       =  t(:host)
                       | :&nbsp;
                      = event.user.name
                    p
                      = strip_tags(event.description).truncate(150)
      div class="row text-center"
        = will_paginate @events, renderer: BootstrapPagination::Rails

app/views/events/new.html.slim
div class="container"
  div class="row"
     div class="bs-docs-section clearfix"
       div class="row"
         div class="page-header"
           div class="jumbotron"
            div class="row"
             div class="col-lg-12"
               h2 class="display-3"
                 = t(:add)
                 | &nbsp;
                 = t(:event)
               == render 'form'

               = link_to t(:back), events_path

app/views/events/show.html.slim
div class="clearfix"
  div class="container"
    div class="page-header"
      div class="row"
        | &nbsp;
      div class="row"
        div class="modal fade" id="show_ticket"
          div class="modal-dialog modal-lg" role="document"
            div class="modal-content"
              div class="modal-header"
                h5 class="modal-title"
                  = t(:ticket_view)
                  button type="button" class="close" data-dismiss="modal" aria-label="Close"
                    span aria-hidden="true"
                     | &times;
                div class="modal-body"
                  div id="ticket_content"
                div class="modal-footer"
                  span id="link_to_attendee"
                  | &nbsp;
                  button type="button" class="btn btn-secondary" data-dismiss="modal"
                    = t(:close)
      div class="row"
        div class="col-lg-10"
         | &nbsp;
        div class="col-lg-2 text-right"
          - if can? :update, @event
            = link_to t(:edit), edit_event_path(@event)
            '|
            = link_to t(:attendees), event_attendees_path(@event)
            '|
          = link_to t(:back), events_path
      div class="row"
        figure class="figure"
          = image_tag @event.image.url(:event), class: "figure-img img-fluid rounded"
      div class="row"
        | &nbsp;
      div class="row"
        div class="list-group"
          div class="list-group-item list-group-item-action flex-column align-items-start"
            div class="d-flex w-100 justify-content-between"
              div class="row"
                div class="col-lg-2 text-center bg-light"
                  h1 class="display-2"
                    = @event.start_at.strftime("%b")
                  h2 class="display-3 text-danger"
                    = @event.start_at.strftime("%d")
                  h3 class="display-4"
                    = @event.start_at.strftime("%Y")
                div class="col-lg-8"
                  h2 class="font-weight-bold"
                    = @event.title
                  p
                    strong
                      = t(:hosted_by)
                      | : &nbsp;
                    = link_to @event.user.name, user_custom_path(@event.user_id,@event.user.name)
                  - unless @event.location.nil?
                    p
                      strong
                        = t(:location)
                        | : &nbsp;
                      = @event.location
                  p
                    strong
                      = t(:from)
                      | : &nbsp;
                    = @event.start_at.strftime("%I:%M %p")
                    | &nbsp;
                    strong
                      = t(:until)
                      | : &nbsp;
                    = @event.end_at.strftime("%I:%M %p")
                  p
                    = link_to t(:add_to_calendar), event_calendar_download_path(@event)
                  - unless @event.ticket_url.nil?
                    - unless @event.ticket_url.empty?
                      p
                        strong
                          = t(:tickets)
                          | : &nbsp;
                        = link_to @event.ticket_url, @event.ticket_url, target: "_blank"
                  = social_share_button_tag(@event.title,desc: @event.description)
                div class="col-lg-2"
                  - unless @event.tickets.empty? || @event.end_at<DateTime.now
                    - if @available
                      - if user_signed_in?
                        - if @attendee.nil?
                          = link_to t(:event_registration), attendees_path(attendee: {ticket_id: @event.tickets.first.id}), method: :post , class: "btn btn-success btn-lg btn-block", data: {confirm: t(:sure_your_want_to_attend_this_event)},id: "Event_Registration", remote: true
                        - else
                          = link_to t(:view_your_ticket), attendee_path(@attendee), remote: true, class: "btn btn-success btn-lg btn-block"
                      - else
                        = link_to t(:event_registration), new_user_session_path, class: "btn btn-warning btn-lg btn-block"
                    - else
                      - if @event.ticket_url.include? request.domain
                        = link_to t(:sold_out), "#", class: "btn btn-success btn-lg disabled", disabled: true
                      - else
                        = link_to t(:get_tickets), @event.ticket_url, target: "_blank", class: "btn btn-success btn-lg"
                  span id="view_your_ticket"
      div class="row"
        div class="col-lg-12"
          = sanitize @event.description
      div class="row"
        div class="col-lg-12"
          - unless @event.latitude.nil?
            = map(container_id: "show_map",center: {latlng: ["#{@event.latitude}", "#{@event.longitude}"],zoom: 14}, markers: [{latlng: ["#{@event.latitude}", "#{@event.longitude}"]}])
      div class="row"
        | &nbsp;
      div class="row"
          - if @community.nil?
            = @event.organizer
          - else
            div class="list-group"
              div class="list-group-item list-group-item-action flex-column align-items-start"
                div class="d-flex w-100 justify-content-between"
                  div class="row"
                    div class="col-lg-2 text-center bg-light"
                      = image_tag @community.logo.url(:thumb), class: "img-fluid rounded"
                    div class="col-lg-10"
                      strong
                        = @community.name
                      p
                        = sanitize @community.information
      div class="row"
        div class="col-lg-10"
         | &nbsp;
        div class="col-lg-2 text-right"
          - if can? :update, @event
            = link_to t(:edit), edit_event_path(@event)
            '|
          = link_to t(:back), events_path