config/routes.rb
Rails.application.routes.draw do

  resources :attendees
  resources :tickets
  resources :ticket_types
  get "events/:id/downloads" => "events#calendar_download", as: 'event_calendar_download'
  get "event/:year/:month/:day" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ }
  get "event/:year/:month/:day/*anything" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ }
  get 'privacy' => 'home#privacy',  :defaults => { :id => '2' }, as: 'privacy'
  get 'news/:id/edit' => 'news#edit'
  get 'communities/:id/edit' => 'communities#edit'
  get 'news/:id/*anything' => 'news#show', as: 'news_custom'
  get 'communities/:id/*anything' => 'communities#show', as: 'community_custom'
  get 'user/:id/*anything' => 'user#show', as: 'user_custom'
  resources :events do
    resources :attendees, only: [:index]
  end
  resources :user, only: [:show]
  resources :communities
  resources :carousels
  resources :pages
   mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :news
  get 'home/index'

  devise_for :users,  :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/news.rb
class News < ApplicationRecord
  belongs_to :user
  has_one :news_content,inverse_of: :news
  validates :user, presence: true
  validates :title, presence: true, length: {minimum: 6, maximum: 255}, allow_nil: false
  accepts_nested_attributes_for :news_content
  before_save :set_published_date
  has_paper_trail

  def set_published_date
    if self.publish
      self.published_at=Date.today
    end
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index,:show]
  before_action :set_news, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /news
  # GET /news.json
  def index
    @news = News.paginate(:page => params[:page],:per_page =>9 ).where("publish=true ", params[:id]).order('created_at DESC')

  end

  # GET /news/1
  # GET /news/1.json
  def show
    set_meta_tags og: {
                  url: "#{request.base_url + request.original_fullpath}",
                  type: "website",
                  title: "#{@news.title} Software Libre y Codigo Abierto Panama",
                  description: @news.news_content.content,
                  site_name: "floss-pa",
                  image: "https://floss-pa.net/images/logo.png}"
                  }
    set_meta_tags twitter: {
                card:  "summary",
                description: @news.news_content.content,
                title: @news.title,
                creator: "@flosspa",
                image: {
                        _:       "https://floss-pa.net/images/logo.png}",
                        width:  100,
                        height: 100,
                },
                domain: "Floss-pa"
                }


    set_meta_tags  author: user_custom_path(@news.user,@news.user.name.gsub(/\s/,'-'))
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = current_user.news.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :keywords, :language, :publish, :published_at, news_content_attributes: [:id,:content,:bootsy_image_gallery_id])
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.slim
= form_for @news do |f|
  - if @news.errors.any?
    #error_explanation
      div class="form-group row"
        h2 = "#{pluralize(@news.errors.count, "error")} prohibited this news from being saved:"
        ul
          - @news.errors.full_messages.each do |message|
            li = message

  div class="form-group row"
    = f.label t(:title), class: "form-input-label"
    = f.text_field :title, required: true, minlength: "6", maxlenght: "50", class: "form-control"
    small id="titlelHelp" class="form-text text-muted"
      = t(:title_will_display_on_the_page_and_work_as_search_index)
  div class="form-group row"
    = f.label t(:keywords), class: "form-input-label"
    = f.text_field :keywords, class: "form-control"
    small id="emailHelp" class="form-text text-muted"
      = t(:keyworks_will_help_search_engines_to_spread_the_news)
  div class="form-group row"
    - if params[:action]=="edit"
      = f.fields_for :news_content do |content_form|
        = content_form.bootsy_area :content, rows: 20, required: true, minlength:50, class: "form-control"
    - else
      = f.fields_for :news_content, NewsContent.new do |content_form|
        = content_form.bootsy_area :content, cols: 122, rows: 40
  div class="form-check"
    div class="form-check-label"
      = f.check_box :publish,  class: "form-check-input"
      | &nbsp;
      = f.label t(:publish)
    = t(:only_published_items_will_be_display_to_all_users)
  div class="form-group row"
    = f.submit t(:save), class: "btn btn-primary"

app/views/news/edit.html.slim
div class="container"
  div class="row"
     div class="bs-docs-section clearfix"
       div class="row"
         div class="page-header"
           div class="jumbotron"
             div class="col-lg-12"
               h2 class="display-3"
                 = t(:edit)
                 | &nbsp;
                 = t(:news)
       
               == render 'form'
       
             => link_to t(:show), @news
             '|
             =< link_to t(:back), news_index_path

app/views/news/index.html.slim
div class="container"
  div class="row"
    div class="page-header"
      div class="col-lg-12"
        h1
          = t(:news)
          | :
        - @news.each do |news|
            div class="jumbotron"
              div class="row"
                h2 class="display-3"
                 div class="col-lg-10"
                  = link_to news_custom_path(news.id, news.title.gsub(/\s/,'-'))
                    = news.title
                 div class="col-lg-2"
                  small
                    = time_ago_in_words(news.published_at)
              div class="row"
                div class="col-lg-12"
                  = t(:by)
                  | :&nbsp;
                  = link_to news.user.name, user_custom_path(news.user.id,news.user.name.gsub(/\s/,'-'))
              div class="row"
               | &nbsp;
              div class="row"
               div class="col-lg-12"
                p class="lead"
                  = sanitize news.news_content.content
              hr class="my-4"
                = social_share_button_tag(news.title,:url => "#{url_for(news_url(news))}", desc: news.news_content.content)
              div class="row"
               | &nbsp;
        = will_paginate @news, renderer: BootstrapPagination::Rails

app/views/news/new.html.slim
div class="container"
  div class="row"
     div class="bs-docs-section clearfix"
       div class="row"
         div class="page-header"
         div class="jumbotron"
           div class="col-lg-12"
             h2 class="display-3"
               = t(:add)
               | &nbsp;
               = t(:news)
     
             == render 'form'
     
           = link_to 'Back', news_index_path

app/views/news/show.html.slim
div class="container"
  div class="row"
    div class="bs-docs-section clearfix"
      div class="row"
        div class="page-header"
          div class="jumbotron"
            div class="row"
             div class="col-lg-12"
              - if notice
                div class="alert alert-dismissible alert-danger"
                  button type="button" class="close" data-dismiss="alert"
                    | &times;
                  = notice
              div class="col-lg-10"
               | &nbsp;
       
              div class="col-lg-2"
                - if can? :update, @news
                  => link_to t(:edit), edit_news_path(@news)
                  '|
                =< link_to t(:back), news_index_path
              h2 class="display-3"
                = @news.title
              div class="col-lg-10"
               = t(:by)
               | :&nbsp;
               = @news.user.name
              div class="col-lg-2"
                = @news.published_at.strftime("%B %d, %Y") unless @news.published_at.nil?
              div class="col-lg-12"
               p class="lead"
                 = sanitize @news.news_content.content
              div class="col-lg-10"
                = social_share_button_tag(@news.title,url: "#{url_for news_url(@news)}",desc: strip_tags(@news.news_content.content))
              div class="col-lg-2"
                - if can? :update, @news
                 => link_to 'Edit', edit_news_path(@news)
                '|
                =< link_to 'Back', news_index_path