config/routes.rb
Rails.application.routes.draw do

  resources :attendees
  resources :tickets
  resources :ticket_types
  get "events/:id/downloads" => "events#calendar_download", as: 'event_calendar_download'
  get "event/:year/:month/:day" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ }
  get "event/:year/:month/:day/*anything" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ }
  get 'privacy' => 'home#privacy',  :defaults => { :id => '2' }, as: 'privacy'
  get 'news/:id/edit' => 'news#edit'
  get 'communities/:id/edit' => 'communities#edit'
  get 'news/:id/*anything' => 'news#show', as: 'news_custom'
  get 'communities/:id/*anything' => 'communities#show', as: 'community_custom'
  get 'user/:id/*anything' => 'user#show', as: 'user_custom'
  resources :events do
    resources :attendees, only: [:index]
  end
  resources :user, only: [:show]
  resources :communities
  resources :carousels
  resources :pages
   mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :news
  get 'home/index'

  devise_for :users,  :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/community.rb
class Community < ApplicationRecord
  belongs_to :user
  has_many :members
  has_paper_trail
  validates :user, presence: :true
  validates :name, presence: :true, uniqueness: true, length: {minimum: 6, maximum: 255}, allow_nil: false
  validates :information, presence: true,  length: {minimum: 10}, allow_nil: false
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  after_create :add_first_member

  private
  def add_first_member
    member=Member.new
    member.community_id = self.id
    member.user_id = self.user_id
    member.admin = true
    member.save
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_community, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /communities
  # GET /communities.json
  def index
    @communities = Community.paginate(:page => params[:page],:per_page =>9 ).where(params[:id]).order('created_at DESC')
  end

  # GET /communities/1
  # GET /communities/1.json
  def show
    set_meta_tags og: {
                  url: "#{request.base_url + request.original_fullpath}",
                  type: "website",
                  title: "#{@community.name} Software Libre y Codigo Abierto Panama",
                  description: @community.information,
                  site_name: "floss-pa",
                  image: "https://floss-pa.net/images/logo.png}"
                  }
    set_meta_tags twitter: {
                card:  "summary",
                description: @community.information,
                title: @community.name,
                creator: "@flosspa",
                image: {
                        _:       "https://floss-pa.net/images/logo.png}",
                        width:  100,
                        height: 100,
                },
                domain: "Floss-pa"
                }


    set_meta_tags  author: user_custom_path(@community.user,@community.user.name.gsub(/\s/,'-'))

  end

  # GET /communities/new
  def new
    @community = Community.new
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities
  # POST /communities.json
  def create
    @community = current_user.communities.new(community_params)

    respond_to do |format|
      if @community.save
        format.html { redirect_to @community, notice: 'Community was successfully created.' }
        format.json { render :show, status: :created, location: @community }
      else
        format.html { render :new }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1
  # PATCH/PUT /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to @community, notice: 'Community was successfully updated.' }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1
  # DELETE /communities/1.json
  def destroy
    @community.destroy
    respond_to do |format|
      format.html { redirect_to communities_url, notice: 'Community was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_params
      params.require(:community).permit(:user_id, :name, :information, :logo, :site)
    end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_form.html.slim
= form_for @community do |f|
  - if @community.errors.any?
    #error_explanation
      h2 = "#{pluralize(@community.errors.count, "error")} prohibited this community from being saved:"
      ul
        - @community.errors.full_messages.each do |message|
          li = message

  div class="form-group row"
    = f.label t(:name), class: "form-input-label"
    = f.text_field :name, required: true, minlength: "6", maxlenght: "50", class: "form-control"
    small id="titlelHelp" class="form-text text-muted"
      = t(:name_that_describe_your_community)
  div class="form-group row"
    = f.label t(:information), class: "form-input-label"
    = f.bootsy_area :information, rows: 20, required: true, minlength: "10", class: "form-control"
    small id="titlelHelp" class="form-text text-muted"
      = t(:add_all_the_information_that_best_describe_your_community)
  div class="form-group row"
    = f.label t(:logo), class: "form-input-label"
    = f.file_field :logo , class: "form-control-file"
    small id="titlelHelp" class="form-text text-muted"
      = t(:it_is_always_a_nice_idea_to_have_a_logo)
  div class="form-group row"
    = f.label t(:site), class: "form-input-label"
    = f.text_field :site, class: "form-control"
    small id="titlelHelp" class="form-text text-muted"
      = t(:add_the_url_of_your_community)
  div class="form-group row"
    = f.submit t(:save), class: "btn btn-primary"

app/views/communities/edit.html.slim
div class="container"
  div class="row"
    div class="bs-docs-section clearfix"
      div class="row"
        div class="page-header"
          div class="jumbotron"
            div class="row"
             div class="col-lg-12"
               h2 class="display-3"
                 = t(:edit)
                 | &nbsp;
                 = t(:community)
               == render 'form'
             => link_to t(:show), @community
             '|
             =< link_to t(:back), communities_path

app/views/communities/index.html.slim
div class="bs-docs-section clearfix"
 div class="container"
  div class="row"
    div class="page-header"
      div class="col-lg-12"
        h1
          = t(:communities)
          | :
        - @communities.each do |community|
            div class="jumbotron"
              div class="row"
                h2 class="display-3"
                 div class="col-lg-8"
                  = link_to community_custom_path(community.id,community.name.gsub(/\s/,'-'))
                    = community.name
                 div class="col-lg-4"
                 small
                    = time_ago_in_words(community.created_at)
              div class="row"
                div class="col-lg-12"
                  = t(:by)
                  | :&nbsp;
                  = link_to community.user.name, user_custom_path(community.user,community.user.name.gsub(/\s/,'-'))
              div class="row"
               | &nbsp;
              div class="row"
               div class="col-lg-12"
                p class="lead"
                  = sanitize community.information
              hr class="my-4"
                = social_share_button_tag(community.name, url: "#{url_for community_url(community)}", desc: community.information, image: community.logo.url)
              div class="row"
               | &nbsp;
        = will_paginate @communities, renderer: BootstrapPagination::Rails

app/views/communities/new.html.slim
div class="container"
 div class="bs-docs-section clearfix"
  div class="row"
    div class="page-header"
    div class="jumbotron"
      div class="col-lg-12"
        h2 class="display-3"
          = t(:add)
          | &nbsp;
          = t(:community)
        == render 'form'
      = link_to t(:back), communities_path

app/views/communities/show.html.slim
div class="container"
  div class="row"
    div class="bs-docs-section clearfix"
      div class="row"
        div class="page-header"
          div class="jumbotron"
            div class="row"
             div class="col-lg-12"
               - if notice
                 div class="alert alert-dismissible alert-danger"
                   button type="button" class="close" data-dismiss="alert"
                     | &times;
                   = notice
               div class="col-lg-10"
                 | &nbsp;
               div class="col-lg-2"
                 - if can? :update, @community
                   = link_to t(:edit), edit_community_path(@community)
                   '|
                 = link_to t(:back), communities_path
             div class="col-lg-12"
               | &nbsp;
               div class="col-lg-4" style="text-align: center"
                  h2 class="display-3"
                    = @community.name
                  = image_tag @community.logo.url(:thumb)
                  p class="lead"
                    = link_to @community.name,@community.site,target: "_blank"
               div class="col-lg-8"
                   = sanitize(@community.information)
             div class="col-lg-12"
               div class="col-lg-10"
                 = social_share_button_tag(@community.name, url: "#{url_for community_url(@community)}", desc: @community.information, image: @community.logo.url)
               div class="col-lg-2"
                - if can? :update, @community
                  => link_to t(:edit), edit_community_path(@community)
                  '|
                =< link_to t(:back), communities_path